[package]
name = "rxing_test"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
opencv = "0.95.1"
rxing = "0.8.0"

[[bin]]
name = "rxing_test"
path = "src/rxing_test.rs"

[[bin]]
name = "rustcv_test"
path = "src/rustcv_test.rs"