#to use with Pi5
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

#to use with PiZero
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

#install linker: sudo apt install gcc-aarch64-linux-gnu
#run: cargo build --release --target aarch64-unknown-linux-gnu
#copy binary: chmod +x /home/filepath
